name: Default CI Pipeline

on: [push, pull_request]

jobs:
  setup-and-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.os }} ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: npm 7
      # npm workspaces requires npm v7 or higher
        run: npm i -g npm@7 --registry=https://registry.npmjs.org
      - name: Install
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Test
        run: npm run test
